name: practice
services:
  devcontainer:
    build:
      context: .devcontainer
      dockerfile: ../Dockerfile
    volumes:
      - .:/workspaces/practice
      - /home/<host-username>/.ssh:/home/practice/.ssh:cached
      # - /home/<host-username>/.cache/gitstatus:/home/practice/.cache/gitstatus:cached
      - /home/<host-username>/.config/nvim:/home/practice/.config/nvim:cached
      - /home/<host-username>/.local/share/nvim:/home/practice/.local/share/nvim:cached
      - /home/<host-username>/.local/state/nvim:/home/practice/.local/state/nvim:cached
    environment:
      - HOST_USERNAME=<host-username>
      - UV_LINK_MODE=copy
    command: sleep infinity
