name: practice
services:
  devcontainer:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/practice
      - /home/ttranpphu/.ssh:/home/practice/.ssh:cached
      - /home/ttranpphu/.config/nvim:/home/practice/.config/nvim:cached
      - /home/ttranpphu/.local/share/nvim:/home/practice/.local/share/nvim:cached
      - /home/ttranpphu/.local/state/nvim:/home/practice/.local/state/nvim:cached
    environment:
      - HOST_USERNAME=ttranpphu
      - UV_LINK_MODE=copy
    command: sleep infinity
