from .bulb_switch import Solution as BulbSwitch
from .can_be_valid import Solution as CanBeValid
from .can_jump import Solution as CanJump
from .find_median_sorted_arrays import Solution as FindMedianSortedArrays
from .height_checker import Solution as HeightChecker
from .is_long_pressed_name import Solution as IsLongPressedName
from .length_of_longest_substring import Solution as LengthOfLongestSubstring
from .min_difference import Solution as MinDifference
from .my_pow import Solution as MyPow
from .solve_n_queens import Solution as SolveNQueens
from .total_n_queens import Solution as TotalNQueens
from .two_sum import Solution as TwoSum
