services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/practice:cached
      - /home/ttranpphu/.ssh:/home/practice/.ssh:cached
    environment:
      - UV_LINK_MODE=copy
    command: sleep infinity
    network_mode: "service:mongo"

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ../db:/data/db:cached
