[package]
name = "practice"
version = "0.1.0"
edition = "2021"

[dependencies]
leetcode = { version = "0.1.0", path = "leetcode" }
logger = { version = "0.1.0", path = "logger" }
macros = { version = "0.1.0", path = "macros" }
sudoku = { version = "0.1.0", path = "sudoku" }
