[package]
name = "practice"
version = "0.1.0"
edition = "2021"

[dependencies]
leetcode = { version = "0.1.0", path = "leetcode" }
macro_utils = { version = "0.1.0", path = "macro_utils" }
sudoku = { version = "0.1.0", path = "sudoku" }
