from interview import *
from .test_util import test_ordered_list_equal


def test_intect():
    test_ordered_list_equal(
        cases=[
            {
                "n": 4,
                "initially_infected": {0},
                "interactions": [(0, 0, 1), (1, 2), (0, 1, 2)],
                "expect": [0, 1, -1, -1],
            },
            {
                "n": 20,
                "initially_infected": {0, 1, 2, 3, 4},
                "interactions": [
                    (0, 0, 1),
                    (1, 2),
                    (0, 1, 2),
                    (0, 1, 3),
                    (0, 1, 4),
                    (1, 5),
                    (0, 1, 6),
                    (0, 5, 6),
                    (0, 6, 7),
                    (0, 7, 8),
                    (0, 8, 9),
                    (0, 9, 10),
                    (0, 10, 11),
                    (0, 11, 12),
                    (0, 12, 13),
                    (0, 13, 14),
                    (0, 14, 15),
                    (0, 15, 16),
                    (0, 16, 17),
                    (0, 17, 18),
                    (0, 18, 19),
                ],
                "expect": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    -1,
                    7,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                ],
            },
        ],
        solution=Infect().infect,
    )
